### ISSUE TITLE
SBMLBioModelsImportTest not passing anymore

### ISSUE THREAD

**Issue by bmoreau** [TheCoSMoCompany/biopredyn#92]
= Description =
- Find and fix the origin of the test failure.

= Context =
- !SBMLBioModelsImportTest tests the access to the !BioModels data base; queries to !BioModels - through the !BioServices python package - does not seem to work anymore.

= Success criteria =
- Models can be imported from !BioModels data base.

= Error log =
{{{
cobra/solvers/glpk_solver.py:14 [NON-XML-CHAR-0x1B][1;31mRuntimeWarning[NON-XML-CHAR-0x1B][0m: PyGLPK compiled on GLPK 4.43, but runtime is GLPK 4.45
# E
## ERROR: test_biomodels_import (**main**.SBMLTestCase)

Traceback (most recent call last):
  File "/home/bertrand/dev-git/biopredyn/build/Prototype/testing/test.py", line 42, in test_biomodels_import
    source='urn:miriam:biomodels.db:BIOMD0000000001')
  File "/home/bertrand/.local/lib/python2.7/site-packages/biopredyn-0.1.0-py2.7.egg/biopredyn/model.py", line 68, in **init**
    self.init_tree()
  File "/home/bertrand/.local/lib/python2.7/site-packages/biopredyn-0.1.0-py2.7.egg/biopredyn/model.py", line 219, in init_tree
    s = BioModels()
  File "/usr/local/lib/python2.7/dist-packages/bioservices/biomodels.py", line 114, in **init**
    super(BioModels, self).**init**(name="BioModels", url=BioModels._url, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/bioservices/services.py", line 223, in __init__
    super(WSDLService, self).**init**(name, url, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/bioservices/services.py", line 86, in **init**
    super(Service, self).**init**(level=verbose)
  File "/usr/local/lib/python2.7/dist-packages/easydev/logging_tools.py", line 48, in **init**
    self.debugLevel = level
  File "/usr/local/lib/python2.7/dist-packages/easydev/logging_tools.py", line 61, in _set_level
    raise ValueError("The level of debugging must be in %s " %valid_level)
ValueError: The level of debugging must be in ['INFO', 'DEBUG', 'WARNING', 'CRITICAL', 'ERROR'] 

---

Ran 1 test in 0.001s

FAILED (errors=1)
}}}

**Comment by bmoreau** [comment]
_Imported from trac issue 56.  Created by bmoreau on 2014-09-30T18:06:14, last modified: 2014-10-01T10:36:31_
